### PR TITLE
Merge from original nonstriater

### PR DESCRIPTION
**Pull request by chengmo03013106**

### CODE REVIEW

**Comment by chengmo03013106** [comment]
Merge from original nonstriater

**Comment by nonstriater** [comment]
good job!  but why delete  `C语言代码规范.md`  file ?

**Comment by chengmo03013106** [comment]
Hi

I am really sorry about this 

I am not familiar with github’s operations….

It’s supposed to merge your files into my branched which fork from you before….

 

I will be careful to do the operations on the codes.

Anyway, I want to do some contributions on it.

 

 

发件人: 移动开发小冉 <notifications@github.com> 
发送时间: 2019年1月29日 16:17
收件人: nonstriater/Learn-Algorithms <Learn-Algorithms@noreply.github.com>
抄送: Martin <chmhou@sina.com>; State change <state_change@noreply.github.com>
主题: Re: [nonstriater/Learn-Algorithms] Merge from original nonstriater (#13)

 

good job! but why delete C语言代码规范.md file ?

**Comment by nonstriater** [comment]
you can follow these steps:
1. fork again
2. git pull & fix conflict  at your local repo
3. push & start pull request

make sure you use the latest code before you start a pull request.

by the way,  frequent pull request are better than commit too much at one time~

thx for your job again

**Comment by chengmo03013106** [comment]
> you can follow these steps:
> 
> 1. fork again
> 2. git pull & fix conflict  at your local repo
> 3. push & start pull request
> 
> make sure you use the latest code before you start a pull request.
> 
> by the way, frequent pull request are better than commit too much at one time~
> 
> thx for your job again

Thank you for the tips.
I will close this request later and send the new request after making sure the differents between mine.

**Pull request closed without merging**
